services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/data/pg-data:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql